SliceTracker.py

Check for installed VolumeClip extension while loading SliceTracker

---

SliceTracker.py

This pull request fixes issue #24

Add dilation of the segmentation mask to improve registration robustness

---

SliceTracker.py

This PR also fixes 
issue #11
issue #10
issue #43 
issue #44
issue #45 
issue #46
issue #47
issue #48
issue #49
issue #51

Refactoring Code

---

SliceTracker.py

this PR fixes:
issue #4 
issue #42 
issue #52 
issue #54

Saving data to output

---

SliceTracker.py

Further bugs and enhancements

---

SliceTracker.py

fixes #99 
fixes #111 
- volumes for series are not loaded till they are really needed (better performance)

Resetting directory observer and prompt user if patient IDs don't match

---

CMakeLists.txt
SliceTracker.py
SliceTrackerRegistration.py
SliceTrackerUtils/Constants.py
SliceTrackerUtils/RegistrationData.py
SliceTrackerUtils/ZFrameRegistration.py
SliceTrackerUtils/decorators.py
SliceTrackerUtils/mixins.py

fixes partially #4
fixes #106 
fixes #108
fixes #113
fixes #116
fixes #117 
fixes #119

Reorganized views, moving targets, target visibility, slice annotations, saving results, extracting registration into independent module

---

SliceTracker.py
SliceTrackerUtils/RegistrationData.py
SliceTrackerUtils/constants.py
SliceTrackerUtils/helpers.py

fixes #87 
fixes #146 
fixes #148 
fixes #152 
fixes #156 
fixes #157 
fixes #158

FOV, Visual Feedback of hole/depth validity, fixing target visibility 

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/RegistrationData.py
SliceTracker/SliceTrackerUtils/configuration.py

disabling skipping Cover Prostate/Template
fixes #87 
fixes #160 
fixes #162

Using SliceTracker settings instead of configuration class all the time

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerRegistration.py
SliceTracker/SliceTrackerUtils/RegistrationData.py
SliceTracker/SliceTrackerUtils/events.py

fixes #169
fixes #170
fixes #171
fixes #173
fixes #176
fixes #177
fixes #178

Improvements regarding registration, user feedback (display of processing information)

---

docs/user_guide/bx_tracking.md
docs/user_guide/initial_reg.md
docs/user_guide/zframe.md

fixes https://www.gitbook.com/book/fedorov/slicetracker/discussions/6

ENH: Consistent usage of Z-Frame throughout the user guide

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerRegistration.py
SliceTracker/SliceTrackerUtils/constants.py

fixes #191 
fixes #193 
also please merge https://github.com/SlicerProstate/SlicerProstate/pull/25

Handling completed session as read only, added training mode

---

SliceTracker/Resources/default.cfg
SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/configuration.py

Default evaluation layout Four-Up and added key event observers for cursor distance computation

---

SliceTracker/SliceTracker.py

BUG: Starting storescp immediately after receiving preop (issue #203)

---

SliceTracker/Resources/default.cfg
SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/configuration.py

Demo mode and flicker, rock mode opacity issue fixes

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/constants.py
SliceTracker/SliceTrackerUtils/events.py

- changed sample data url
- implemented own SampleDownloader for being able to cancel download

sample url and SampleDownloader

---

README.md

@tokjun please let me know if this looks good to you, or if I missed anything

ENH: improve acknowledgments

---

SliceTracker/SliceTracker.py

related to https://github.com/SlicerProstate/SlicerProstate/pull/32

Adaption to SlicerProstate changes and removed print command

---

SliceTracker/SliceTracker.py

Fix label naming and volume clip model displaying

---

SliceTracker/SliceTracker.py
SliceTracker/VolumeClipToLabel.py

depends on https://github.com/SlicerProstate/SlicerProstate/pull/42
fixes #226
fixes #233
fixes #234
fixes #235

Button for displaying module settings, saving VolumeClip data and fixing needle out of range in Four-Up

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/exceptions.py
SliceTracker/VolumeClipToLabel.py

ENH: continuing processing unfinished preprocessed data and fixing completion errors whiles saving

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/helpers.py
startSlicelet_Ubuntu.sh

fixed messed up NewCaseSelectionNameWidget and implemented Slicelet

---

CMakeLists.txt
SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerRegistration.py
SliceTracker/SliceTrackerUtils/algorithms/zFrameRegistration.py
SliceTracker/SliceTrackerUtils/configuration.py
SliceTracker/SliceTrackerUtils/helpers.py
SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/sessionData.py
SliceTracker/SliceTrackerUtils/steps/base.py
SliceTracker/SliceTrackerUtils/steps/overview.py
SliceTracker/SliceTrackerUtils/steps/plugins/case.py
SliceTracker/SliceTrackerUtils/steps/plugins/results.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/automatic.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/manual.py
SliceTracker/SliceTrackerUtils/steps/plugins/targeting.py
SliceTracker/SliceTrackerUtils/steps/plugins/targets.py
SliceTracker/SliceTrackerUtils/steps/plugins/training.py
SliceTracker/SliceTrackerUtils/steps/segmentation.py
SliceTracker/SliceTrackerUtils/steps/zFrameRegistration.py
SliceTracker/SliceTrackerZFrameRegistration.py
SliceTracker/VolumeClipToLabel.py
puml/SliceTracker.puml
puml/SlicerDevelopmentToolbox.puml

* moved SliceTracker specific IncomingDataMessageBox here

ENH: changed dependency from SlicerProstate to SlicerDevelopmentToolbox:

---

SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/steps/base.py

WIP: fixes for bugs introduced during refactoring process

---

SliceTracker/CMakeLists.txt
SliceTracker/Resources/version.json
SliceTracker/Resources/version.json.in
SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/sessionData.py
SliceTracker/SliceTrackerUtils/steps/base.py
SliceTracker/SliceTrackerUtils/steps/evaluation.py
SliceTracker/SliceTrackerUtils/steps/overview.py
SliceTracker/SliceTrackerUtils/steps/plugins/case.py
SliceTracker/SliceTrackerUtils/steps/plugins/charts.py
SliceTracker/SliceTrackerUtils/steps/plugins/results.py
SliceTracker/SliceTrackerUtils/steps/plugins/targeting.py
SliceTracker/SliceTrackerUtils/steps/plugins/targets.py
SliceTracker/SliceTrackerUtils/steps/segmentation.py
SliceTracker/SliceTrackerUtils/steps/zFrameRegistration.py
SliceTracker/SurfaceCutToLabel.py

fixes #287 
fixes #296
fixes #300 
fixes #309

WIP: fixing bugs and work on milestone

---

SliceTracker/SliceTrackerUtils/algorithms/automaticProstateSegmentation.py

- got stuck for several minutes caused by dilating output label
fixes #315

BUG: fixed automatic segmentation of preop data (issue #315)

---

SliceTracker/SliceTrackerUtils/steps/segmentation.py

BUG: temporarily commenting out code that crashes Slicer (issue #318)

---

SliceTracker/Resources/default.cfg
SliceTracker/SliceTrackerUtils/algorithms/automaticProstateSegmentation.py
SliceTracker/SliceTrackerUtils/configuration.py
SliceTracker/SliceTrackerUtils/session.py

fixes #324 
TODO: add pattern option to add regexp to default.cfg that would allow identifying pre procedural t2 depending on a pattern

BUG: convert series description to lower and find ax and t2 (issue #324)

---

SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/sessionData.py
SliceTracker/SliceTrackerUtils/steps/evaluation.py
SliceTracker/SliceTrackerUtils/steps/overview.py
SliceTracker/SliceTrackerUtils/steps/plugins/case.py
SliceTracker/SliceTrackerUtils/steps/plugins/charts.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/automatic.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/base.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/manual.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentationValidator.py
SliceTracker/SliceTrackerUtils/steps/plugins/training.py
SliceTracker/SliceTrackerUtils/steps/segmentation.py
SliceTracker/SurfaceCutToLabel.py
doc/output_example.json
doc/output_schema.json

* added more information about registration, segmentation times
* prompting operator about who approved/rejected registration result in order to have some more information
* some modification done for segmentation validation popup
* added more information to json output:
* timestamps for registration and segmentation
* consentGivenBy (for approved and rejected results)
* subsection `series` holding information about the series type and received time 
fixes #321
fixes #302
fixes #330
fixes #336
for reference https://github.com/SlicerProstate/SliceTracker/pull/329
for reference https://github.com/QIICR/SlicerDevelopmentToolbox/commit/a1574252ff68a1138f48a29f38a39113bbb96156
TODO's after merging this PR

WIP: Bug fixes and enhancements (#320, #321) 

---

SliceTracker/SliceTrackerUtils/session.py

fixes partially #322
* made some changes on SDT
* now SliceWidgetConfirmYesNoDialog uses its own slice widget instead
of taking the Red one

BUG: size of SliceWidgetConfirmYesNoMessageBox unpredictable

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/helpers.py
SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/steps/overview.py
SliceTracker/SliceTrackerUtils/steps/plugins/results.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentation/manual.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentationValidator.py
SliceTracker/SliceTrackerUtils/steps/plugins/targets.py

Addresses #172, and adds compatibility for Qt5.
Qt5 Compatibility changes:
* Fix annotation positioning for high DPI displays
* Fix QSettings return value when input is boolean
* Change depreciated Qt methods 
* Split IncomingDataMessageBox into two classes based on Qt version

BUG: Qt5 compatibility and tweaks

---

SliceTracker/Resources/default.cfg
SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/configuration.py
SliceTracker/SliceTrackerUtils/helpers.py

- added module setting for being able to change the number of digits used for case directories
- resetting the progress bar on case close
fixes #322

Fix minor issues

---

SliceTracker/SliceTrackerUtils/steps/plugins/charts.py

BUG: displacement plots now work even after clearing scene (issue #351)

---

SliceTracker/SliceTracker.py
SliceTracker/SliceTrackerUtils/preopHandler.py
SliceTracker/SliceTrackerUtils/session.py
SliceTracker/SliceTrackerUtils/steps/overview.py
SliceTracker/SliceTrackerUtils/steps/plugins/charts.py
SliceTracker/SliceTrackerUtils/steps/plugins/segmentationValidator.py

* reorganized code
* moved code to separate python script file
fixes #353

Fixes interruption while validating automatic segmentation caused by DICOM import
